---
ansible_connection: local
openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/test"
    tags:
    - projects
- object: project-acls
  content:
  - name: "ci-cd-acl"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/project-acl/template.yml"
    params: "{{ playbook_dir }}/params/project-acl/all"
    tags:
    - project-acl
  - name: "labs-dev-acl"
    namespace: "{{ dev_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/project-acl/template.yml"
    params: "{{ playbook_dir }}/params/project-acl/all"
    tags:
    - project-acl
  - name: "labs-dev-acl"
    namespace: "{{ test_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/project-acl/template.yml"
    params: "{{ playbook_dir }}/params/project-acl/all"
    tags:
    - project-acl