---
ansible_connection: local
openshift_cluster_content:
- galaxy_requirements: "{{ playbook_dir }}/galaxy_requirements.yml"
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/test"
    tags:
    - projects